# Generated by Django 6.0.3 on 2026-03-20 17:18
# NOTE: Address creation was moved to 0004_address (on the canonical branch).
# This migration is kept as a no-op to preserve the dependency chain.

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
