# Generated by Django 6.0 on 2026-03-20 19:00
# This migration is a no-op: the Address model was already created by 0002_address.
# Kept only to preserve the dependency chain leading to 0005_merge_0002_address_0004_address.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_wechat_openid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Address table is created by 0002_address; no operation needed here.
    ]
