# Generated by Django 6.0 on 2026-03-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_address'),
        ('account', '0004_address'),
    ]

    operations = [
    ]
