# Generated by Django 6.0 on 2026-03-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wechat_openid',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
