# Generated by Django 6.0 on 2025-12-11 07:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '设备分类', 'verbose_name_plural': '设备分类'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': '二手设备', 'verbose_name_plural': '二手设备'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='上传时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category', verbose_name='设备分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition_level',
            field=models.CharField(choices=[('99', '99成新'), ('95', '95成新'), ('90', '9成新'), ('80', '8成新'), ('70', '7成新及以下')], default='90', max_length=10, verbose_name='成色'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='详细描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location_city',
            field=models.CharField(blank=True, max_length=50, verbose_name='所在城市'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location_province',
            field=models.CharField(max_length=50, verbose_name='所在省份'),
        ),
        migrations.AlterField(
            model_name='product',
            name='machinery_type',
            field=models.CharField(choices=[('excavator', '挖掘机'), ('loader', '装载机'), ('bulldozer', '推土机'), ('crane', '起重机'), ('forklift', '叉车'), ('pump_truck', '泵车'), ('roller', '压路机'), ('grader', '平地机'), ('other', '其他机械')], default='other', max_length=20, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacture_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='出厂年份'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='价格（元）'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='卖家'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='设备标题'),
        ),
        migrations.AlterField(
            model_name='product',
            name='working_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='工作小时数'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d/', verbose_name='设备图片'),
        ),
    ]
