# Generated by Django 6.0.3 on 2026-03-20 17:18
# Banner table is created by 0003_banner; this migration only handles Favorite/Order alterations.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': '收藏', 'verbose_name_plural': '收藏'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='store.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', '待付款'), ('pending_receipt', '待收货'), ('completed', '已完成'), ('cancelled', '已取消'), ('pending', '待支付'), ('paid', '已支付'), ('shipped', '已发货')], default='pending_payment', max_length=20),
        ),
    ]
