# Generated by Django 6.0 on 2026-03-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/%d/', verbose_name='轮播图')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='跳转链接')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序（越小越靠前）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'ordering': ['order'],
            },
        ),
    ]
