# Generated by Django 6.0 on 2026-03-13 17:58
# NOTE: Banner creation was moved to 0003_banner_alter_favorite_options_alter_favorite_product_and_more.
# This migration is kept as a no-op to preserve the dependency chain.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_alter_favorite_options_and_more'),
    ]

    operations = []

