# Generated by Django 6.0 on 2026-03-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_favorite_options_alter_favorite_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', '待付款'), ('pending_receipt', '待收货'), ('completed', '已完成'), ('cancelled', '已取消'), ('pending', '待支付'), ('paid', '已支付'), ('shipped', '已发货')], default='pending_payment', max_length=20),
        ),
    ]
