# Generated by Django 6.0 on 2026-03-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_banner_alter_favorite_options_alter_favorite_product_and_more'),
        ('store', '0005_alter_order_status'),
    ]

    operations = [
    ]
