# Generated by Django 6.0.3 on 2026-03-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_merge_20260321_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='收货地址快照'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', '待付款'), ('pending_shipment', '待发货'), ('pending_receipt', '待收货'), ('completed', '已完成'), ('cancelled', '已取消'), ('pending', '待支付'), ('paid', '已支付'), ('shipped', '已发货')], default='pending_payment', max_length=20),
        ),
    ]
